#!/usr/bin/env python3
"""Red Sox outfield-logjam strategy deck (python-pptx, no external tooling).

Team-level reframe of the Duran analysis: the OF is a surplus asset; the
pitching is a strength; spend the surplus on bats. Embeds pre-rendered charts
from ../figures/.
"""
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches as In, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "figures"
OUT = ROOT / "outputs" / "Red_Sox_Trade_Deadline.pptx"

# palette, dark "night game" broadcast theme
BG = "0B1220"          # page
PANEL = "121E33"       # cards
PANEL2 = "1A2740"      # emphasis card
NAVY = "EAF0F8"        # primary display text (was navy-on-light)
RED = "E8615A"; GREEN = "58C08D"; GOLD = "E3B14E"
INK = "D9E1EF"; MUTED = "93A0B6"; WHITE = "F4F7FC"; LINE = "26334E"
HEAD = "Arial"; BODY = "Arial"; MONO = "Courier New"

W, H = 13.333, 7.5
ASPECT = {"01": 1.60, "04": 1.60, "07": 10/5.8, "08": 10/6.4,
          "09": 1504/649, "10": 2087/679, "12": 1.62, "13": 1.68,
          "14": 9/5.4, "15": 9/5.4, "16": 9/5.2, "17": 11.4/5.6,
          "18": 12.6/5.2}

# ---- live numbers (regenerated by run_all.py; deck never hardcodes them)
import datetime as _dt
import json

DAYS_LEFT = max(0, (_dt.date(2026, 8, 3) - _dt.date.today()).days)


def ordn(n):
    n = int(n)
    if 10 <= n % 100 <= 20:
        return f"{n}th"
    return f"{n}{ {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th') }"

_D = json.load(open(ROOT / "data" / "deadline.json"))
_BOS = _D["bos"]
ODDS = f"{_D['verdict']['odds']*100:.0f}%"
RUNDIFF = f"{int(_BOS['run_diff']):+d}"
PYTH = f".{float(_BOS['pythag'])*1000:.0f}"
_w, _l = int(_BOS["W"]), int(_BOS["L"])
PCT = f".{1000*_w/(_w+_l):.0f}"
_stk = str(_BOS.get("streak", ""))
STREAK = _stk if (_stk.startswith("W") and _stk[1:].isdigit()
                  and int(_stk[1:]) >= 13) else "W13"

_BAT = json.load(open(ROOT / "data" / "battery.json"))["per_catcher"]
WONG9 = f"{_BAT['Connor Wong']['RA9']:.2f}"
NARV9 = f"{_BAT['Carlos Narváez']['RA9']:.2f}"
_BM = json.load(open(ROOT / "data" / "battery_model.json"))["fe"]
FE_EST = f"{_BM['catcher_effect_wong_minus_narvaez']*1000:+.0f}"
FE_CI = (f"[{_BM['ci95'][0]*1000:+.0f}, {_BM['ci95'][1]*1000:+.0f}]")
_AAAA = json.load(open(ROOT / "data" / "aaaa.json"))
_ACQ = json.load(open(ROOT / "data" / "acquisition.json"))
_ABT = json.load(open(ROOT / "data" / "aaaa_backtest.json"))
_XC = json.load(open(ROOT / "data" / "xcontact.json"))
NBB = f"{_XC['n_batted_balls']:,}"
DEC10 = f"{[d for d in _XC['deciles'] if d['decile'] == 10][0]['resid_base']*1000:+.0f}"
DUR_PREM = f"{_XC['duran']['speed_premium_wobacon']*1000:+.0f}"


def C(hexs):
    return RGBColor.from_string(hexs)


def txt(slide, x, y, w, h, runs, size=16, color=INK, bold=False, font=BODY,
        align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, italic=False,
        space_after=4, line_spacing=1.0, wrap=True):
    tb = slide.shapes.add_textbox(In(x), In(y), In(w), In(h))
    tf = tb.text_frame
    tf.word_wrap = wrap
    tf.vertical_anchor = anchor
    for m in ("margin_left", "margin_right", "margin_top", "margin_bottom"):
        setattr(tf, m, 0)
    if isinstance(runs, str):
        runs = [[(runs, {})]]
    for i, para in enumerate(runs):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.space_after = Pt(space_after)
        p.line_spacing = line_spacing
        if isinstance(para, str):
            para = [(para, {})]
        for t, o in para:
            r = p.add_run(); r.text = t
            f = r.font
            f.size = Pt(o.get("size", size)); f.bold = o.get("bold", bold)
            f.italic = o.get("italic", italic); f.name = o.get("font", font)
            f.color.rgb = C(o.get("color", color))
    return tb


def card(slide, x, y, w, h, fill=PANEL, line=LINE, radius=0.06):
    sh = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,
                                In(x), In(y), In(w), In(h))
    sh.fill.solid(); sh.fill.fore_color.rgb = C(fill)
    if line:
        sh.line.color.rgb = C(line); sh.line.width = Pt(1)
    else:
        sh.line.fill.background()
    sh.shadow.inherit = False
    try:
        sh.adjustments[0] = radius
    except Exception:
        pass
    return sh


def dot(slide, x, y, d, fill=RED, text=None, tcolor="0B1220", size=15):
    """Square scoreboard tag (replaces the old circle motif)."""
    sh = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,
                                In(x), In(y), In(d), In(d))
    sh.fill.solid(); sh.fill.fore_color.rgb = C(fill); sh.line.fill.background()
    sh.shadow.inherit = False
    try:
        sh.adjustments[0] = 0.18
    except Exception:
        pass
    if text is not None:
        tf = sh.text_frame; tf.word_wrap = False
        p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
        r = p.add_run(); r.text = text
        r.font.size = Pt(size); r.font.bold = True; r.font.name = MONO
        r.font.color.rgb = C(tcolor)
    return sh


def image(slide, key, x, y, max_w, max_h, name):
    src0 = FIG / "dark" / name
    if not src0.exists():
        src0 = FIG / name
    try:
        from PIL import Image as _Im
        with _Im.open(src0) as im:
            a = im.width / im.height   # true aspect, never stretch
    except Exception:
        a = ASPECT.get(key, 1.6)
    w = max_w; hh = w / a
    if hh > max_h:
        hh = max_h; w = hh * a
    ix = x + (max_w - w) / 2
    src = FIG / "dark" / name
    if not src.exists():
        src = FIG / name
    slide.shapes.add_picture(str(src), In(ix), In(y), In(w), In(hh))
    return ix, y, w, hh


def eyebrow(slide, text, x=0.62, y=0.42, color=RED):
    txt(slide, x, y, 11, 0.3, [[("// " + text.upper(),
        {"color": color, "bold": True, "size": 12, "font": MONO})]],
        space_after=0)


def title(slide, text, x=0.62, y=0.72, w=12.1, size=30, color=NAVY):
    txt(slide, x, y, w, 0.95, [[(text, {"size": size, "bold": True,
        "font": HEAD, "color": color})]], space_after=0, line_spacing=1.0)


def footer(slide, dark=False):
    c = "5E6B84"
    txt(slide, 0.62, 7.12, 12.1, 0.3,
        [[("BOS // OUTFIELD STRATEGY", {"color": RED, "size": 8,
           "font": MONO, "bold": True}),
          ("   STATCAST / FANGRAPHS / MLB STATS API / SPOTRAC · JULY 2026",
           {"color": c, "size": 8, "font": MONO})]], space_after=0)


def bg(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = C(color)


prs = Presentation()
prs.slide_width = In(W); prs.slide_height = In(H)
blank = prs.slide_layouts[6]


def new(color=BG):
    s = prs.slides.add_slide(blank); bg(s, color); return s


# ---------------------------------------------------------------- 1 TITLE
s = new("0E1830")
dot(s, 0.62, 0.62, 0.34, fill=RED)
txt(s, 1.05, 0.6, 10, 0.4, [[("BOSTON RED SOX  ·  TRADE DEADLINE 2026",
    {"color": "C9D2E3", "bold": True, "size": 13})]], space_after=0)
txt(s, 0.62, 2.15, 12.1, 2.0, [
    [("Red Sox Trade Deadline", {"size": 46, "bold": True,
      "font": HEAD, "color": WHITE})],
    [("Thoughts", {"size": 46, "bold": True, "font": HEAD,
      "color": RED})],
], space_after=2, line_spacing=1.0)
txt(s, 0.62, 4.35, 11.6, 1.0, [[(
    "After an incredible push, the Sox are in a position to be buyers "
    "before this trade deadline. A breakdown of our new acquisition, "
    "Curtis Mead, and what else the Sox need to do for a deep playoff "
    f"run. {DAYS_LEFT} days to August 3.",
    {"size": 17, "color": "D3D9E6"})]], line_spacing=1.12)
txt(s, 0.62, 6.6, 12, 0.4, [[("A data-driven roster case study · July 2026",
    {"color": "8C97AC", "size": 12, "italic": True})]], space_after=0)

# ---------------------------------------------------------------- 2 SITUATION
s = new()
eyebrow(s, "The setup")
title(s, "A contender by run differential")
stats = [(f"{_w}-{_l}", "record", "holding the final wild card"),
         (RUNDIFF, "run differential",
          f"outplaying their {PCT} record all season"),
         (ODDS, "playoff odds",
          "10,000 sims of the rest of the season (fig. 12)")]
cw, gap = 3.83, 0.31
for i, (big, lab, sub) in enumerate(stats):
    x = 0.62 + i * (cw + gap)
    card(s, x, 2.05, cw, 2.35)
    txt(s, x + 0.28, 2.28, cw - 0.5, 0.9, [[(big, {"size": 44, "bold": True,
        "font": HEAD, "color": RED if i == 0 else NAVY})]], space_after=0)
    txt(s, x + 0.3, 3.28, cw - 0.55, 0.4, [[(lab, {"size": 15, "bold": True,
        "color": NAVY})]], space_after=0)
    txt(s, x + 0.3, 3.66, cw - 0.55, 0.7, [[(sub, {"size": 12.5,
        "color": MUTED})]], line_spacing=1.05)
txt(s, 0.62, 4.75, 12.1, 1.4, [
    [("A month ago the easy take was sell. ",
      {"bold": True, "color": INK, "size": 15}),
     ("The outfield jam, still ",
      {"color": INK, "size": 15}),
     ("masked by Roman Anthony's injury", {"bold": True, "color": RED, "size": 15}),
     (", is now a buyer's depth chart: the surplus funds the deadline instead "
      "of a teardown.", {"color": INK, "size": 15})],
], line_spacing=1.2)
footer(s)

# ------------------------------------------------------------ 2b THE RACE
s = new()
eyebrow(s, "The verdict")
title(s, "Buy, but keep it small")
image(s, "12", 0.4, 1.7, 8.0, 4.6, "12_playoff_race.png")
tx = 8.75
rules = [("Hold Duran", RED,
          "Duran has had a miserable season, but his underlying numbers "
          "are better than they seem. Positive regression candidate. "
          "Let him build up his value and flip in the offseason."),
         ("Keep the vets", NAVY,
          "Gray, Chapman, Contreras should not be sold now. Sell branch "
          "reopens only if the gap blows out by Aug 1."),
         ("Don't disturb the clubhouse", GREEN,
          "Back-end starter, reliever, RHH.")]
yy = 1.95
for head, col, body in rules:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.3, [[(head, {"bold": True, "size": 14.5,
        "color": NAVY})], [(body, {"size": 12, "color": MUTED})]],
        line_spacing=1.08, space_after=2)
    yy += 1.45
footer(s)

# ---------------------------------------------------------------- 3 KEEP CORE
s = new()
eyebrow(s, "Keep")
title(s, "The young, cheap, controllable outfield core")
core = [("Roman Anthony", "LF · age 22", "3.8", "$2.6M · 8yr/$130M ext",
         "Franchise bat. Untouchable. On the IL now, back in 2027."),
        ("Ceddanne Rafaela", "CF · age 25", "3.2", "$2.0M · 8yr/$50M",
         "Elite center-field glove + SS/utility flex. Premium position, "
         "controlled cheap."),
        ("Wilyer Abreu", "RF · age 27", "2.8", "$0.8M · pre-arb → 2029",
         "Best surplus on the roster: plus RF glove, above-average LH bat.")]
cw, gap = 3.83, 0.31
for i, (nm, pa, war, sal, note) in enumerate(core):
    x = 0.62 + i * (cw + gap)
    card(s, x, 1.95, cw, 3.9)
    txt(s, x + 0.3, 2.2, cw - 0.55, 0.5, [[(nm, {"size": 19, "bold": True,
        "font": HEAD, "color": NAVY})]], space_after=0)
    txt(s, x + 0.3, 2.72, cw - 0.55, 0.3, [[(pa, {"size": 12.5, "bold": True,
        "color": RED})]], space_after=0)
    txt(s, x + 0.3, 3.25, cw - 0.55, 0.9, [[(war, {"size": 40, "bold": True,
        "font": HEAD, "color": GREEN})]], space_after=0)
    txt(s, x + 0.3, 4.18, cw - 0.55, 0.3, [[("projected WAR / yr",
        {"size": 11, "color": MUTED})]], space_after=0)
    txt(s, x + 0.3, 4.55, cw - 0.55, 0.35, [[(sal, {"size": 12, "bold": True,
        "color": INK})]], space_after=0)
    txt(s, x + 0.3, 4.95, cw - 0.55, 0.85, [[(note, {"size": 11.5,
        "color": MUTED})]], line_spacing=1.06)
txt(s, 0.62, 6.05, 12.1, 0.5, [[("Three spots, locked. Everything else flexes "
    "around them.", {"italic": True, "size": 14, "color": NAVY})]],
    space_after=0)
footer(s)

# ---------------------------------------------------------------- 4 MOVE
s = new()
eyebrow(s, "Move")
title(s, "The 4th Outfield Spot")
cw = 5.86
data = [(0.62, "Jarren Duran", "LF/CF · 29 · $7.7M", RED,
         [("Movable piece.", "Controllable through 2028; above-average "
           "at true talent (~110 wRC+). Redundant behind the core and the "
           "priciest of the young group."),
          ("Hold at the deadline.", "Duran has had a miserable season, "
           "but his underlying numbers are better than they seem. "
           "Positive regression candidate. Let him build up his value "
           "and flip in the offseason.")]),
        (0.62 + cw + 0.33, "Masataka Yoshida", "DH · 32 · $18.6M", MUTED,
         [("The contract, not the bat.", "He's hitting: above-average "
           "wRC+, .340-class OBP, one of MLB's lowest strikeout rates. "
           "$18.6M for a DH with below-average pop is still underwater "
           "as an asset."),
          ("Keep him in the lineup.", "Gonzalez covers the tougher "
           "lefties. Platoon the DH spot and let it ride.")])]
for x, nm, meta, accent, rows in data:
    card(s, x, 1.95, cw, 3.95)
    txt(s, x + 0.32, 2.22, cw - 0.6, 0.5, [[(nm, {"size": 21, "bold": True,
        "font": HEAD, "color": NAVY})]], space_after=0)
    txt(s, x + 0.32, 2.78, cw - 0.6, 0.32, [[(meta, {"size": 13, "bold": True,
        "color": accent})]], space_after=0)
    yy = 3.35
    for head, body in rows:
        dot(s, x + 0.32, yy + 0.05, 0.13, fill=accent)
        txt(s, x + 0.58, yy, cw - 0.95, 1.2, [[
            (head + " ", {"bold": True, "color": INK, "size": 13.5}),
            (body, {"color": MUTED, "size": 13})]], line_spacing=1.08)
        yy += 1.25
txt(s, 0.62, 6.15, 12.1, 0.5, [[("With Roman's status up in the air, hold "
    "both outfielders through this season.", {"italic": True, "bold": True,
    "size": 13.5, "color": GOLD})]], line_spacing=1.05)
footer(s)

# ---------------------------------------------------------------- 5 DURAN LUCK
s = new()
eyebrow(s, "Don't sell low")
title(s, "Duran's 2026 is unlucky")
ix, iy, iw, ih = image(s, "01", 0.5, 1.75, 6.9, 4.55,
                       "01_babip_vs_league.png")
tx = 7.7
rows = [("2024 was more what we should expect", RED,
         "BABIP .344 vs xBABIP .333; xwOBA .340 legit. Legs are still "
         "there, and defense is definitely improved."),
        ("2026 is the real anomaly", NAVY,
         "wOBA .263 BELOW its .293 xwOBA, 34 to 43 pts under his own "
         "norm; BABIP .238 vs .309 expected."),
        ("The legs are fine", GOLD,
         "Speed, baserunning and fielding all still plus. No injury."),
        ("True talent ≈ his 2025 (~110 wRC+)", GREEN,
         "An above-average regular. The 2024 high and 2026 low are tails "
         "around that plateau.")]
yy = 1.82
for head, col, body in rows:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 5.0, 1.2, [[(head, {"bold": True, "size": 13.5,
        "color": NAVY})], [(body, {"size": 11.6, "color": MUTED})]],
        line_spacing=1.07, space_after=2)
    yy += 1.16
txt(s, tx, yy + 0.03, 5.0, 0.6, [[("Wait for the rebound.",
    {"italic": True, "bold": True, "size": 12.5,
    "color": RED})]], line_spacing=1.05)
footer(s)

# ---------------------------------------------------------------- 5b REBOUND SIM
s = new()
eyebrow(s, "The rebound math")
title(s, "The rebound is likely for Duran")
image(s, "09", 0.4, 1.7, 8.3, 4.1, "09_rebound_probability.png")
tx = 9.0
txt(s, tx, 1.8, 3.7, 0.35, [[("P(REST-OF-SEASON wRC+ ≥ 100)",
    {"size": 11.5, "bold": True, "color": MUTED})]], space_after=0)
txt(s, tx, 2.15, 3.7, 0.85, [
    [("69%", {"size": 34, "bold": True, "font": HEAD, "color": GREEN}),
     ("  healthy prior", {"size": 12.5, "color": MUTED})],
    [("47%", {"size": 34, "bold": True, "font": HEAD, "color": RED}),
     ("  erosion-blended", {"size": 12.5, "color": MUTED})],
], space_after=2, line_spacing=1.0)
txt(s, tx, 3.85, 3.7, 0.35, [[("EXPECTED OFFSEASON TRADE VALUE",
    {"size": 11.5, "bold": True, "color": MUTED})]], space_after=0)
txt(s, tx, 4.2, 3.7, 0.8, [
    [("$22M", {"size": 24, "bold": True, "font": HEAD, "color": NAVY}),
     (" vs ", {"size": 13, "color": MUTED}),
     ("$18M", {"size": 24, "bold": True, "font": HEAD, "color": NAVY})],
    [("either way, well above the ~$10M a July sale fetches",
      {"size": 11.5, "color": MUTED})],
], space_after=2, line_spacing=1.05)
txt(s, 0.62, 6.15, 12.1, 0.7, [[("The honest line: ", {"size": 13.5,
    "bold": True, "color": RED}),
    ("the 22-point probability gap is the price of the worse chase / whiff / "
     "hard-hit rates. Hold-through-2026 survives the erosion stress test, "
     "but with less confidence in the rebound narrative itself.",
     {"size": 13.5, "color": INK})]], line_spacing=1.12)
footer(s)

# ------------------------------------------------------- 5c EROSION VERDICT
s = new()
eyebrow(s, "The tiebreaker")
title(s, "Swing Stats")
image(s, "10", 0.5, 1.7, 12.33, 3.2, "10_erosion_decomposition.png")
cards = [("74.5 mph", "avg bat speed 2026, up from 72.7 in '24", GREEN,
          "Duran is swinging harder, longer and steeper than ever."),
         ("29% whiff vs 95+", "up from 16% in '24", RED,
          "Whiffs on a rising bat speed. Breaking-ball chase actually "
          "improved, the problem is on velocity."),
         ("60 / 40", "re-weighted scenario odds → 60% rebound", NAVY,
          "Approach is fixable (see his own 2022→23 chase overhaul); the "
          "tools a buyer prices are intact.")]
cw, gap = 3.83, 0.31
for i, (big, lab, col, body) in enumerate(cards):
    x = 0.62 + i * (cw + gap)
    card(s, x, 5.05, cw, 1.85)
    txt(s, x + 0.26, 5.2, cw - 0.5, 0.5, [[(big, {"size": 21, "bold": True,
        "font": HEAD, "color": col}),
        ("  " + lab, {"size": 10.5, "color": MUTED})]], space_after=0,
        line_spacing=1.0)
    txt(s, x + 0.26, 5.78, cw - 0.5, 1.0, [[(body, {"size": 10.8,
        "color": INK})]], line_spacing=1.07)
footer(s)

# ---------------------------------------------------------------- 6 AGE CURVE
s = new()
eyebrow(s, "Context")
title(s, "Aging doesn't explain the drop")
image(s, "04", 3.05, 1.65, 7.25, 4.5, "04_age_curve_overlay.png")
txt(s, 0.62, 6.35, 12.1, 0.7, [[("2024 → 2026 wRC+ fell ~70 points; a normal "
    "age 27→29 curve predicts only ~7. ", {"size": 14, "color": INK}),
    ("The gap is mean-reversion from an inflated peak plus a 2026 bad-luck "
     "tail, not a skill cliff.", {"size": 14, "bold": True, "color": NAVY})]],
    line_spacing=1.1)
footer(s)

# ------------------------------------------------------- 6b POSITIONAL AUDIT
s = new()
eyebrow(s, "If they buy, where?")
title(s, "The roster's biggest hole is the Duran slump itself")
image(s, "13", 0.4, 1.7, 8.0, 4.6, "13_positional_audit.png")
tx = 8.75
finds = [("LF −31: internal fix", RED,
          "Duran's regression, now sheltered by a Jahmai Jones platoon, "
          "plus Anthony's eventual return. Free."),
         ("SS −18: the true target", NAVY,
          "One controllable infield stabilizer is the only lineup trade "
          "that fits the odds."),
         ("Bullpen: quiet weakness", GOLD,
          "ERA top-10 but FIP and reliever WAR rank far worse, it will "
          "regress without help."),
         ("The Contreras twist", GREEN,
          "The winter's reported sell candidate is now their best hitter. "
          "Moving him would be met with outrage.")]
yy = 1.9
for head, col, body in finds:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.2, [[(head, {"bold": True, "size": 13.5,
        "color": NAVY})], [(body, {"size": 11.6, "color": MUTED})]],
        line_spacing=1.07, space_after=2)
    yy += 1.22
footer(s)

# ------------------------------------------------------ 6b1 QUAD-A AUDIT
s = new()
eyebrow(s, "The supporting cast")
title(s, "Career years everywhere. Could mean regression")
image(s, "17", 0.4, 1.75, 8.0, 4.55, "17_aaaa_audit.png")
tx = 8.75
_nh = _AAAA['n_career_high']
_regs = _AAAA.get('regulars', [])
_reg_txt = ", ".join(f"{r['name'].split()[-1]} "
                     f"{r['delta']*1000:+.0f} OPS pts"
                     for r in _regs) or "none this year"
finds = [(f"{_AAAA['n']} AAAA contributors on the roster", RED,
          "Waiver claims, up-down arms and career minor-leaguers holding "
          f"real roles, {_AAAA['total_war']:+.1f} WAR combined."),
         (f"{_nh} career best{'' if _nh == 1 else 's'}, "
          f"{_AAAA['n_rookie']} rookies", GOLD,
          "The vets are beating their own track records; the rookies "
          "have no baseline at all."),
         ("The regulars are hot too", TEAL_D := "5FB6D9",
          f"Same screen on the everyday lineup: {_reg_txt}. Expect good, "
          "not scorching, from here."),
         ("History backs the fade", NAVY,
          f"2016-25, {_ABT['hitters']['n']} hitter and "
          f"{_ABT['arms']['n']} reliever cases: the median journeyman "
          "kept only "
          f"{_ABT['hitters']['median_retention']*100:.0f}% of a "
          "career-best first half (fig. 20)."),
         ("Buy Buy Buy", GREEN,
          "Pick up a seasoned reliever and a right-handed hitter.")]
yy = 1.78
for head, col, body in finds:
    dot(s, tx, yy + 0.04, 0.15, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.1, [[(head, {"bold": True, "size": 12.5,
        "color": NAVY})], [(body, {"size": 10.8, "color": MUTED})]],
        line_spacing=1.05, space_after=1)
    yy += 1.06
footer(s)

# --------------------------------------------------- 6b1b THE BASE RATE
s = new()
eyebrow(s, "The base rate")
title(s, "Career-year first halves usually give it back")
image(s, "20", 0.4, 1.7, 8.0, 4.6, "20_aaaa_backtest.png")
tx = 8.75
_bh, _ba = _ABT["hitters"], _ABT["arms"]
finds = [(f"{_bh['n'] + _ba['n']} historical cases", RED,
          f"2016-2025: {_bh['n']} hitters and {_ba['n']} relievers with "
          "the same profile as Boston's AAAA group: thin track record, "
          "age 26+, career-best first half."),
         (f"Median kept {_bh['median_retention']*100:.0f}%", NAVY,
          "The typical hitter held only "
          f"{_bh['median_retention']*100:.0f}% of his surge after July; "
          f"relievers {_ba['median_retention']*100:.0f}%."),
         ("A third fell all the way back", GOLD,
          f"{_bh['back_to_career_pct']}% of hitters and "
          f"{_ba['back_to_career_pct']}% of relievers finished the "
          "second half at or below their career level."),
         ("So the surge is rented", GREEN,
          "Plan for the median, not the heater: replace borrowed "
          "production before August returns it.")]
yy = 1.9
for head, col, body in finds:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.2, [[(head, {"bold": True, "size": 13.5,
        "color": NAVY})], [(body, {"size": 11.6, "color": MUTED})]],
        line_spacing=1.07, space_after=2)
    yy += 1.22
footer(s)

# ---------------------------------------------------------- 6b2 BATTERY MAP
s = new()
eyebrow(s, "The chemistry veto")
title(s, "Don't Mess Up The Pitching Staff")
image(s, "14", 0.4, 1.7, 8.0, 4.6, "14_battery_map.png")
tx = 8.75
finds = [("The staff works with both", RED,
          f"{WONG9} RA9 with Wong, {NARV9} with Narváez, the "
          "run-prevention core of the season."),
         ("Every arm has a guy. Don't mess with that", NAVY,
          "Gray / Wong. Bennett / Narvaez. Settled, deliberate "
          "assignments across the rotation."),
         ("So: no catcher trade", GREEN,
          "The adjusted model (pitcher/opponent/park controls) finds no "
          f"significant catcher effect: {FE_EST} pts, 95% CI {FE_CI}. "
          "Nothing here for a trade to fix.")]
yy = 1.9
for head, col, body in finds:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.2, [[(head, {"bold": True, "size": 13.5,
        "color": NAVY})], [(body, {"size": 11.6, "color": MUTED})]],
        line_spacing=1.07, space_after=2)
    yy += 1.22
footer(s)

# ---------------------------------------------------------- 6c MOCK TRADES
s = new()
eyebrow(s, "The menu")
title(s, "Three trades that fit, and one walk-away")
trades = [
    ("1 · The pen fix · do it", "RHP Luke Weaver (NYM)", GREEN,
     "For a 45 FV + 40 FV, prospects only, nobody loses a job or an "
     "inning. Elite relief year, signed through '27. The highest-"
     "probability marginal win on the board."),
    ("2 · The stabilizer · if the price holds", "2B Luis Arraez (SFG)",
     NAVY,
     "For Brayan Bello, the first deal that touches the active roster. "
     "Zero prospect cost; Arraez fills a patchwork platoon spot, not a "
     "hot regular's."),
    ("3 · The big swing · probably wait", "SS Zach Neto (LAA)", RED,
     "For Tolle + Bennett + a 45 FV: two arms out of a winning "
     "rotation midseason. Right for the franchise window, and still "
     "there in the winter. Controlled through 2029."),
    ("✗ · The walk-away", "C Shea Langeliers (ATH)", GOLD,
     "The value math worked; the battery map is the veto. No August bat "
     "is worth resetting eight pitcher-catcher pairings on a staff "
     "carrying the season.")]
cw, ch = 5.86, 2.12
pos = [(0.62, 1.85), (0.62 + cw + 0.33, 1.85),
       (0.62, 1.85 + ch + 0.28), (0.62 + cw + 0.33, 1.85 + ch + 0.28)]
for (lab, get, col, body), (x, y) in zip(trades, pos):
    card(s, x, y, cw, ch)
    txt(s, x + 0.28, y + 0.18, cw - 0.55, 0.32, [[(lab.upper(),
        {"size": 11, "bold": True, "color": col})]], space_after=0)
    txt(s, x + 0.28, y + 0.5, cw - 0.55, 0.4, [[(get, {"size": 16.5,
        "bold": True, "font": HEAD, "color": NAVY})]], space_after=0)
    txt(s, x + 0.28, y + 0.95, cw - 0.55, 1.05, [[(body, {"size": 11.6,
        "color": MUTED})]], line_spacing=1.1)
txt(s, 0.62, 6.45, 12.1, 0.5, [[("A menu, not a plan, Boston can afford "
    "about two. ", {"bold": True, "size": 12.5, "color": INK}),
    ("Full value math and verified contracts in the mock-trades memo. "
     "Hypotheticals, not reporting.", {"size": 12.5, "color": MUTED})]],
    space_after=0)
footer(s)

# ------------------------------------------------------- 6d THE REAL TRADE
s = new()
eyebrow(s, "The real trade")
title(s, "They made one: Mead for Early")
image(s, "19", 0.4, 1.62, 8.0, 5.0, "19_mead_fenway.png")
tx = 8.75
_mf = _ACQ["fg"]
finds = [("The deal", RED,
          f"Curtis Mead ({_ACQ['age']}) from Washington for Connelly "
          f"Early: one surplus arm for a {_mf['wRC+']} wRC+ infield bat "
          "with years of club control."),
         ("The Fenway fit", NAVY,
          f"{_ACQ['pull_air_rate']*100:.0f}% pull-air rate, "
          f"{ordn(_ACQ['pull_air_pctile'])} percentile, with a "
          f".{int(_ACQ['wobacon_pull_air']*1000)} wOBA on pulled air "
          "balls. RHB pull-air plays to the Monster."),
         ("Earned, mostly", GOLD,
          f".{int(_ACQ['woba']*1000)} wOBA against a "
          f".{int(_ACQ['xwoba']*1000)} xwOBA, so the breakout has "
          "contact quality behind it. The flag: "
          f"{_ACQ['career']['pa_pre_2026']} PA of "
          f".{int(_ACQ['career']['ops_pre_2026']*1000)} OPS before "
          "this year."),
         ("Menu grade", GREEN,
          "The big-swing shape at half the price, and the infield hole "
          f"filled. The pen fix is still open, {DAYS_LEFT} days left.")]
yy = 1.9
for head, col, body in finds:
    dot(s, tx, yy + 0.04, 0.16, fill=col)
    txt(s, tx + 0.32, yy, 4.1, 1.2, [[(head, {"bold": True, "size": 13.5,
        "color": NAVY})], [(body, {"size": 11.6, "color": MUTED})]],
        line_spacing=1.07, space_after=2)
    yy += 1.22
footer(s)

# ------------------------------------------------- 6e WHY THE TRADE WINS
s = new()
eyebrow(s, "The trade, graded")
title(s, "Why Mead for Early wins for Boston")
_E = _ACQ["arms"].get("Connelly Early", {})
_T = _ACQ["arms"].get("Payton Tolle", {})
_B = _ACQ["arms"].get("Jake Bennett", {})
cw = 5.86
data = [(0.62, "What they gave: Connelly Early", RED,
         [("The ERA flattered him.",
           f"{_E.get('era', 0):.2f} ERA over a {_E.get('fip', 0):.2f} "
           f"FIP, a {_E.get('fip', 0) - _E.get('era', 0):+.2f} gap, the "
           "most of any Boston starter. Sold at peak perception."),
          ("The smallest frame in the pipeline.",
           f"{_E.get('height', chr(54) + chr(39) + ' 3' + chr(34))}, "
           f"{_E.get('weight', 195)} lbs. Durability risk the org's "
           "other arms don't carry.")]),
        (0.62 + cw + 0.33, "What they got: Curtis Mead", GREEN,
         [("A controllable, earned bat.",
           f"{_ACQ['fg']['wRC+']} wRC+ at {_ACQ['age']}, backed by a "
           f".{int(_ACQ['xwoba']*1000)} xwOBA. Years of club control "
           "at the position the audit flagged."),
          ("Built for the park.",
           f"{_ACQ['pull_air_rate']*100:.0f}% pull-air rate "
           f"({ordn(_ACQ['pull_air_pctile'])} percentile). RHB pull-air "
           "plays to the Monster.")])]
for x, nm, accent, rows in data:
    card(s, x, 1.85, cw, 3.6)
    txt(s, x + 0.32, 2.1, cw - 0.6, 0.5, [[(nm, {"size": 17, "bold": True,
        "font": HEAD, "color": NAVY})]], space_after=0)
    yy = 2.75
    for head, body in rows:
        dot(s, x + 0.32, yy + 0.05, 0.13, fill=accent)
        txt(s, x + 0.58, yy, cw - 0.95, 1.3, [[
            (head + " ", {"bold": True, "color": INK, "size": 13}),
            (body, {"color": MUTED, "size": 12.2})]], line_spacing=1.09)
        yy += 1.3
txt(s, 0.62, 5.75, 12.1, 1.0, [[("The factory keeps producing:  ",
    {"bold": True, "size": 14, "color": GOLD}),
    (f"Tolle ({_T.get('height', '6-6')}, {_T.get('weight', 250)} lbs, "
     f"{_T.get('era', 0):.2f} ERA / {_T.get('fip', 0):.2f} FIP) and "
     f"Bennett ({_B.get('height', '6-6')}, {_B.get('weight', 234)} lbs, "
     f"{_B.get('era', 0):.2f} / {_B.get('fip', 0):.2f}) are bigger, "
     "more durable and better by FIP. Boston develops arms; it bought "
     "the bat it could not grow.", {"size": 13, "color": INK})]],
    line_spacing=1.15)
footer(s)

# ---------------------------------------------------------------- 10 CLOSER
s = new("0E1830")
dot(s, 0.62, 0.7, 0.34, fill=RED)
txt(s, 1.05, 0.68, 10, 0.4, [[("BOTTOM LINE", {"color": "C9D2E3",
    "bold": True, "size": 13})]], space_after=0)
lines = [("Play the hand.", f"{ODDS} playoff odds, {RUNDIFF} run "
          "differential, a wild card in hand, buy small (a reliever "
          "first), keep the vets, and let the record keep catching up "
          "to the process."),
         ("Cash the surplus, not the slump.", "Hold Duran through the "
          "deadline; re-price him in winter, extend or trade the 2025 "
          "player, never the unlucky 2026 one."),
         ("Stop fighting the Yoshida deal.", "The bat is back to "
          "average or better; absorb the contract and let it expire.")]
yy = 1.95
for head, body in lines:
    dot(s, 0.7, yy + 0.06, 0.18, fill=RED)
    txt(s, 1.05, yy, 11.4, 1.0, [[(head + "  ", {"bold": True, "size": 21,
        "font": HEAD, "color": WHITE}), (body, {"size": 15, "color": "CDD4E2"})]],
        line_spacing=1.1, space_after=2)
    yy += 1.35
txt(s, 1.05, 6.15, 11.4, 0.8, [[("Confidence: ", {"bold": True, "size": 12.5,
    "color": "9AA6BC"}), ("high that 2024 shouldn't be the anchor and pitching "
    "is a strength; the open question is how much of 2026's skill dip (chase, "
    "whiff, hard-hit are all worse) persists, the one thing to watch before "
    "selling.", {"size": 12.5, "color": "9AA6BC", "italic": True})]],
    line_spacing=1.12)

prs.save(str(OUT))
print(f"wrote {OUT}  ({len(prs.slides.__iter__.__self__._sldIdLst)} slides)")
